### ISSUE TITLE
Ensure agents can use event loops created from external code

### ISSUE THREAD

**Issue by jrriehl** [fetchai/uAgents#124]

**Comment by Archento** [comment]
This is possible for a while now, right?
The following code snippet shows that an externally provided loop (with its own coroutines) will run perfectly fine when started from the agent.

```python
import asyncio

from uagents import Agent, Context

loop = asyncio.get_event_loop()

agent = Agent(
    name="looper",
    seed="<seed>",
    loop=loop,
)

@agent.on_event("startup")
async def startup(ctx: Context):
    ctx.logger.info(">>> Agent is starting up.")

async def coro():
    while True:
        print("doing hard work...")
        await asyncio.sleep(1)

if __name__ == "__main__":
    loop.create_task(coro())
    agent.run()
```
<img width="776" alt="Screenshot 2024-07-19 at 15 37 59" src="https://github.com/user-attachments/assets/0083a26a-baca-4553-8645-d99608b7bdbb">

I think we should clarify which requirements need to be satisfied by a feature like this and if it's feasible to implement.
