### ISSUE TITLE
Request: update to latest Pydantic version

### ISSUE THREAD

**Issue by jrriehl** [fetchai/uAgents#125]
Need to check whether this version changes the computed digests (it probably does).

**Comment by DanielHabenicht** [comment]
Please! This breaks compatibility with deepsearch-toolkit. Resulting in manually executing: `python -m pip install uagents uagents-ai-engine --ignore-installed deepsearch-toolkit`

**Comment by Archento** [comment]
Closing this issue as it was handled in #419
