### ISSUE TITLE
Long runing agent might run out of fund and fails to reregister

### ISSUE THREAD

**Issue by qati** [fetchai/uAgents#190]
The common pattern of running the agent is to use fund_agent_if_low. If the funds are not low enough this won't do anything. If the agent runs for a long time, this might yield to running out of funds, thus registration is failing. This currently requires agents to be monitored and restarted if this is happening. Generic solution would be useful for this for many developers.

**Comment by Archento** [comment]
Hi @qati, we faced the same issue when hosting the agents. Take a look at our approach in the [mobility repo](https://github.com/fetchai/mobility/blob/main/munich_poc/mobility_APIs/utility/hosted_agent.py).
