### ISSUE TITLE
Failing to resolve agent address

### ISSUE THREAD

**Issue by qati** [fetchai/uAgents#191]
In the agents sometime we fail to resolve agent address, it feels a bit probabilistic and not too common, but sometimes simply resolution is failing.

**Comment by jrriehl** [comment]
Can you share the agent address and timestamp next time this happens?

**Comment by luttoo** [comment]
Ok

**Comment by luttoo** [comment]
Hi

**Comment by luttoo** [comment]
from uagents import Agent, Context 
alice = Agent(name="alice", seed="alice recovery phrase")

**Comment by Archento** [comment]
Closed: Outdated, please open a new issue if the problem persists.
