### ISSUE TITLE
FET tokens stuck in old staking platform

### ISSUE THREAD

**Issue by NormOneCA** [fetchai/uAgents#245]
I originally staked my fet tokens on the platform but no longer exists.  I was able to view previously my locked tokens.  Anyway to get my tokens out of that old contract?

**Comment by Archento** [comment]
Hi @NormOneCA, sorry for the late reply. Unfortunately this issue is not linked to the uAgents core framework so please raise it on the [main discussion board](https://github.com/orgs/fetchai/discussions/categories/general) (under general) to get support.
Thank you for your understanding
