### ISSUE TITLE
Error message in console whenever msg is sent to an Agent

### ISSUE THREAD

**Issue by jainsangam805** [fetchai/uAgents#376]
![image](https://github.com/fetchai/uAgents/assets/79426008/c27350ed-391a-4da9-aed0-e7a139bfdabe)

**Comment by Archento** [comment]
Hi @jainsangam805, could you please add a bit more information about the error you're seeing?
What are you trying to achieve, which environment are you using, which versions, etc.

**Comment by Archento** [comment]
Closing this issue as resolved.

If the error persists, please open another ticket and add a bit more context. Thank you.
