### ISSUE TITLE
Example 14 for context broadcast is not working.

### ISSUE THREAD

**Issue by abhifetch** [fetchai/uAgents#386]
Example 14 for context broadcast is not working. [Example 14](https://github.com/fetchai/uAgents/tree/main/python/examples/14-broadcast)
error : 

ERROR:    [charles]: Exception in interval handler: 'Context' object has no attribute 'broadcast'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/uagents/agent.py", line 60, in _run_interval
    await func(ctx)
  File "/Users/abhimanyugangani/Desktop/Fetch.AI/recipe-app/backend/agents/sample.py", line 40, in say_hello
    await ctx.broadcast(proto.digest, message=BroadcastExampleRequest())
          ^^^^^^^^^^^^^
AttributeError: 'Context' object has no attribute 'broadcast'

**Comment by Archento** [comment]
Unfortunately I can't reproduce the error. Please make sure that you use the latest version of `uagents` which is [0.12.2](https://github.com/fetchai/uAgents/releases/tag/v0.12.2) as the broadcast change has been introduced on Mar 6, 2024 with the release of [0.11.0](https://github.com/fetchai/uAgents/releases/tag/v0.11.0)
