### ISSUE TITLE
Refactor agent registration E2E tests

### ISSUE THREAD

**Issue by ejfitzgerald** [fetchai/uAgents#446]
The agent registration tests ultimately are an E2E test that is quite flakey and slows down development. We should:

1. Move the current tests into an integration test set and run them periodically. Lets say every day at midnight. The test results for this should be monitored and reported back to the team
2. The test / code should be refactored so that we can isolate the network from the unit test

**Comment by jrriehl** [comment]
Surprised we didn't already have an issue for this. We already have Almanac registration tests running every hour or so on our continuous testing service, so I'd say it's safe to drop these tests. Ideally, I would suggest that we update these tests to simulate or mock the txs for validation purposes.

**Comment by Archento** [comment]
This was already raised in #251.
I'm going to add your comments there and close this issue.
