### ISSUE TITLE
on_query handler not working as expected

### ISSUE THREAD

**Issue by kshipra-fetch** [fetchai/uAgents#502]
### Prerequisites

- [X] I checked the [documentation](https://fetch.ai/docs) and found no answer to my problem
- [X] I checked the [existing issues](https://github.com/fetchai/uAgents/issues) and made sure there are no similar bug reports

### Category

Bug (unexpected behavior)

### Expected Behavior

The application should be able to send a query to the agent and get back a response from the agent.

### Observed Behavior

The application is not able to deliver the query to the agent and throws the following error in failure logs, when trying it with uagents version 0.15.1. However it works fine with uagents version 0.14.0. 

### To Reproduce

Run the following example with uagents==0.15.1

https://github.com/fetchai/uAgents/tree/main/python/examples/16-on-query-proxy

### Version

0.15.1

### Failure Logs (Optional)

```shell
(.venv) kshipra@MacBook-Pro query-example-github % uvicorn proxy:app      
INFO:     Started server process [45589]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
ERROR:    [dispenser]: Failed to deliver message to agent1qdq4hdfz9djyfs9059gzutfezanyusq27p57sf3xgg85rgvdl0ymsuq03r9 @ ['http://localhost:8001/submit']: ['Failed to send message: Envelope signature is missing']
INFO:     127.0.0.1:59559 - "POST /endpoint HTTP/1.1" 200 OK
```
```


### Additional Information (Optional)

_No response_

**Comment by Archento** [comment]
Thanks for raising this issue. We'll provide a fix for this as soon as possible.
