### ISSUE TITLE
Sending a message 

### ISSUE THREAD

**Issue by dguthner** [fetchai/uAgents#512]
### Prerequisites

- [X] I checked the [documentation](https://fetch.ai/docs) and found no answer to my problem
- [X] I checked the [existing issues](https://github.com/fetchai/uAgents/issues) and made sure there are no similar bug reports

### Category

Bug (unexpected behavior)

### Expected Behavior

During an on_query response from the agent, the agent should be able to send a message to another agent before returning from the query.

### Observed Behavior

When trying to send a message to another agent, the output says "Outgoing Message '<class _(class name)_>' is not a valid replyto received message: model: 67cef9c4eca7f098383d7edefe3670815ba8b11d05b25c550d85a66a2cd0f31c"

### To Reproduce

https://fetch.ai/docs/examples/intermediate/react_example

Follow these steps except within the on_query handler add a "variable = await send(new_agent_address, message)" which tries to send a message to another agent's on_message handler. 

### Version

0.15.1

### Environment Details (Optional)

```markdown
requirements.txt very similar to that on https://fetch.ai/docs/examples/intermediate/react_example
```

### Failure Logs (Optional)

```shell
Outgoing message '<class 'protocols.query.QueryTableRequest'>' is not a valid replyto received message: model:67cef9c4eca7f098383d7edefe3670815ba8b11d05b25c550d85a66a2cd0f31c
```

**Comment by jrriehl** [comment]
This sounds like the second incoming message is not getting a fresh context for some reason, and instead contains the first message as the one being replied to. What do you think @Archento?

**Comment by Archento** [comment]
If you read the output carefully you'll see that indeed the message you're trying to send is not part of the `replies` set that this handler has registered.
`"Outgoing Message '<class (class name)>' is not a valid reply to received message: model: 67cef9c4eca7f098383d7edefe3670815ba8b11d05b25c550d85a66a2cd0f31c"`

If you want to send a message from within a message handler to another agent (either `on_message` or `on_query`) please make sure that either:
- the replies parameter in the handler definition includes your desired message, or
- you omit the replies parameter to bypass outgoing message validation.

Example from the docs:
```python
@NewsAgent.on_query(model=NewsRequest, replies={NewsResponse})  # <-- "replies" parameter
async def query_handler(ctx: Context, sender: str, msg: NewsRequest):
    ...
```
