### ISSUE TITLE
CORS support for REST endpoints [Calhacks]

### ISSUE THREAD

**Issue by divikshrivastava** [fetchai/uAgents#563]
### Prerequisites

- [X] I checked the [documentation](https://fetch.ai/docs) and made sure this feature does not already exist
- [X] I checked the [existing issues](https://github.com/fetchai/uAgents/issues) to make sure this feature has not already been requested

### Feature

CORS is a concept for whitelisting the use of APIs from cross-origin resources, and is generally facilitated by flask-cors or CORS middleware in Python and Node js respectively. However, in the agentic deployment of Fetch AI, there is no direct support of this option and requires to be an essential parameter when creating an Agent.

**Comment by divikshrivastava** [comment]
Also I would love to take a stab at it myself @lrahmani @jrriehl

**Comment by Archento** [comment]
Thank you for the feedback!

The current implementation works on the assumption that the used uvicorn (and in respect starlette) server is capable of accepting and properly implementing the necessary CORS handshake. During testing this seemed to have worked for certain domains but it was no reliable or satisfactory solution so we are aware of the need to update this in the future.
As you can see in [the reference code for the asgi server](https://github.com/fetchai/uAgents/blob/8cf6b90f481a7625c95ae9b0c271c6c1577f9008/python/src/uagents/asgi.py#L191-L196) we do already try to set the necessary headers during initialisation of the server so the next step if that doesn't work as expected is to actually add this middleware logic ourselves.

We are currently working on a major update to the server and it makes sense to add these acknowledgment messages from the agent there but feel free to take a stab at it!
And if it possible we'll take this over to the new server :)

**Comment by jrriehl** [comment]
Should be fixed in latest version (https://github.com/fetchai/uAgents/pull/588). Feel free to reopen if you continue to have issues.
