### ISSUE TITLE
Add documentation about when an endpoint parameter is required for the Bureau class

### ISSUE THREAD

**Issue by flotoria** [fetchai/uAgents#575]
### Prerequisites

- [X] I checked the [documentation](https://fetch.ai/docs) and made sure this feature does not already exist
- [X] I checked the [existing issues](https://github.com/fetchai/uAgents/issues) to make sure this feature has not already been requested

### Feature

While looking at Fetch.ai's uAgents framework documentation, we noticed that our agents were not registering on the Almanac Contract. 

Looking at this [documentation](https://fetch.ai/docs/guides/agents/intermediate/bureau), we noticed that our agents, that were added into a Bureau, were not registering on the Almanac Contract; thus, we could not communicate with the agents at all. We were using the code example in the image below and the documentation specified, and it was not registering on the Almanac Contract.  The endpoint parameter is specified as optional, but in this case, it is required **even** when the agents have an endpoint parameter specified.

![image](https://github.com/user-attachments/assets/bb95843b-82fc-4f35-929c-86aa0a8b8fa1)

It pops up with this warning when no endpoint is provided for the bureau:
```WARNING:  [Risk Analyzer Agent]: No endpoints provided. Skipping registration: Agent won't be reachable.```

In the documentation linked above, there should be more clarification on when the endpoint parameter for the Bureau class needs to be specified. The code examples might need to be updated as well. It would also probably be best to also specify when a bureau needs an endpoint parameter in the logs itself.

Perhaps something similar to:
```[bureau]: No endpoint parameter specified for the bureau. All agents in this bureau won't be reachable.```

### Additional Information (Optional)
Was told to create an issue about this by our Fetch.ai mentors.

**Comment by jrriehl** [comment]
Great suggestion! Sorry you faced some confusion because of this, but it sounds like you resolved it in the end. Thanks for opening the issue and we'll make sure to get this into the docs and the next release.
